language: ruby
rvm:
  - 2.7.1
install: bundle install --retry=3
before_install:
  - gem update bundler
script: rspec
after_success:
  - echo 'everything good!'
deploy:
  provider: rubygems
  gem: subparry_labyrinth_solver
  gemspec: labyrinth.gemspec
  on:
    tags: true
  api_key:
    secure: T5WoDFudpUVgxJkxJQLGb1FKkgLEqL+IlSy4jcCnJYpHKAYPbpGj4NmGhDKiGCuDruAyA4hc9DGPALihAUFjXCCJaOdRdKHxUA+blb9aR+vQpqY8jy1w1A94fGz4Nh0Bipmuhn9hSXgG8JovrjEg/S2CNDgP+HdP5kbCKZsSPLAZ75ElnQ3KAfTeEEWWzVV5hPjYhh84oKk7LZTeW3hzFZtJfMUjdJpDnHveb8q9QNKlngMNrkMq1NNwWH53rJy5oz7nNHdBYm0YV+lWxqxblvH7xVQVGc4GzVoepC5mymjSHkWkr/XzzB3nSI6s5xyD2ncye5v1Ua1GVf/CnjvQgCfD/Q/JWS86595xMHo8z9OMMVYUjcbG71yqLEVOu7QllyRV+SNKHeKpX3AVUx8L1dvfzpiuoz0iAeaHBetOVaSHRmBUILfx/WhognNO3KtK/l3YWOgjX6iDuzOZsMeqMjy2p+jILtpNIywD3ItWs4k5H5J7t6YllpOobWG4utS8pE8YEvGp3hSKGMoohRFqDE2oDIVG9LYcl2GCZkI+Kx9SCUh7b1VSFnFZJM0Wdmyj+2ubpI1EPQgGyQF6mHt/ZMnx2zBYQ1lSwU/zUVPylkMmA3xDOeuaJZnPRkZpN4yGV2xK1UA9ymhIq3XUM8moatTz/nIxJ+Eg9VZcRt2fqi8=
