language: ruby
rvm:
  - 2.7.1

install: bundle install --retry=3

before_install:
  - gem update bundler

script: rspec
after_success:
  - echo 'everything good!'
deploy:
  provider: rubygems
  gem: subparry_labyrinth_solver
  api_key:
    secure: 'WSbqoh30mEsXk00qJOPDbcwBh0LfmvBzFTD25FD+CtemEht6p8GKcIRhjyD09uamJCcKnZYJkXSqtnVejjZPGlITgIIWe9JknyZNzyJSxQA7L0yZnTmQP+3KiwdAc1dikaO/X/w+9zC0sQJyrdbjSFIHdxBkBzwXzE/AsdVgl215522tMeiCwafW2cjQ9FT+rw3yGXGRbnsoWh8NMhiD/AJVEz6gz3tD4J0YMsUR9pK19kSANu00f1EDwHRsMGZUX/Tr4UxpkUiAI8grE2vBpaTY8HYBvE0WBQRdRugkksd5g52tasGJnhdVme8Ni93bmJ5w4waLLpIgdNHnfwfJ5tRbmKlBAHm3ao2ag/2K6dGmDoeM/koEmiM+tNfK8mE7HE/johNZplJGXw5irQ7ObIUlVnIeEY8SaSpKWLTOH4goWuHINNlbwEomM0jSteKM9v4T8Ej0JnkA9o0cvIBf0nRgGskv8lMIZ/676smUVriuB+FBmh+PAyz4yYtP/n87FfsVc1/YvAC2e7GVLL4oPm9YRnmW51o2dI3qaluaMmznFCmwpMToGR/XGlWh3rgKdoUQ41CmVqvVJ6r7CNWf6oeXM2Fp4TYzgsLqySOxV4x5oUZbFkyzpWOWG1ZlmlHUeuhi0tue35JkvrBCQOGSojDnJ7Nw878KEdJDxSWjCdE='
  gemspec: labyrinth.gemspec
  on:
    tags: true
